spring.application.name=projeto-integrador

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?user=postgres.shmnyiwvnykooywizcjv&password=${SUPABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

supabase.service_role_key=${SUPABASE_SERVICE_ROLE_KEY}

spring.datasource.hikari.data-source-properties.prepareThreshold=0

supabase.url=https://shmnyiwvnykooywizcjv.supabase.co
supabase.key=${SUPABASE_KEY}
supabase.bucket=denuncias-imagens

# Limite total da requisição (ex: 30MB para múltiplos arquivos)
spring.servlet.multipart.max-request-size=30MB
# Limite máximo de um único arquivo
spring.servlet.multipart.max-file-size=30MB